### ISSUE TITLE
Error onEnable

### ISSUE THREAD

**Issue by ghost** [BajanVlogs/SuperCrates#1]
`11:47:05] [Server thread/CRITICAL]: Could not save Config /home/arma/plugins/SuperCrates/Items.yml: file_put_contents(/home/arma/plugins/SuperCrates/Items.yml): failed to open stream: No such file or directory`

**Comment by ghost** [comment]
An other issu
`[11:52:16] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'SuperCrates v0.0.1': array_rand() expects parameter 1 to be array, null given on BajanVlogs\SuperCrates\Main
[11:52:16] [Server thread/CRITICAL]: ErrorException: "array_rand() expects parameter 1 to be array, null given" (EXCEPTION) in "SuperCrates-master/src/BajanVlogs/SuperCrates/Main" at line 82`

**Comment by OfficialLilKev** [comment]
Should be fixed now can u test it

**Comment by ghost** [comment]
Same error no change

**Comment by OfficialLilKev** [comment]
Really

**Comment by ghost** [comment]
Yes its issu was due by missing fils

**Comment by ghost** [comment]
Items.yml its on wrong directory

**Comment by OfficialLilKev** [comment]
Its not missing tho so I don't understand this issue lol
