### ISSUE TITLE
Various Issues

### ISSUE THREAD

**Issue by Awzaw** [BajanVlogs/SuperCrates#2]
https://github.com/BajanVlogs/SuperCrates/blob/90f6d803425ddf2daebe5ec6fe831c5e04350aa7/src/BajanVlogs/SuperCrates/Main.php#L227-L269

This should be rewritten -  plugins should exit as soon as possible from functions such as PlayerInteractEvent that are being fired all the time by every player; In the code linked above you are creating a new Vector3s on every PlayerInteractEvent, looping an explode with another Vector3, comparing Vector3s... then last of all checking that `$item->getNamedTag()->key->getValue()` actually matches $crate. You need to figure out the fastest way of determining that you don't need to run any code, then exit the function ASAP.

Also, levels don't appear to be handled at all - is the plugin only supposed to be used in the default world?

**Comment by OfficialLilKev** [comment]
Yes Default level
