### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by ItsLazer** [BajanVlogs/SuperCrates#7]
28.01 18:36:30 [Server] Server thread/CRITICAL ErrorException: "file_put_contents(/plugins/SuperCrates/Items.yml): failed to open stream: No such file or directory" (EXCEPTION) in "src/pocketmine/utils/Config" at line 222
28.01 18:36:30 [Server] Server thread/CRITICAL Could not save Config /plugins/SuperCrates/Items.yml: file_put_contents(/plugins/SuperCrates/Items.yml): failed to open stream: No such file or directory

**Comment by OfficialLilKev** [comment]
Fixed
